### ISSUE TITLE
>> Request failed, Non-200 received getting AUTH cookie: 302

### ISSUE THREAD

**Issue by joeyman178** [ChuckMac/ADRFinder#14]
Running through docker and then locally. Received the following:

Not sure if it's me doing something wrong! Apologies if so. 

2023-01-15 02:04:22 (1) wsgi starting up on http://0.0.0.0:5500
2023-01-15 02:04:22 Exception in thread Thread-5:
2023-01-15 02:04:22 Traceback (most recent call last):
2023-01-15 02:04:22   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
2023-01-15 02:04:22     self.run()
2023-01-15 02:04:22   File "/app/adrfinder/update_worker.py", line 26, in run
2023-01-15 02:04:22     update_handler = fetch_site_status.perform_site_check(datastore=self.datastore)
2023-01-15 02:04:22                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:04:22   File "/app/adrfinder/fetch_site_status.py", line 16, in __init__
2023-01-15 02:04:22     self.headers = self.get_auth_cookie()
2023-01-15 02:04:22                    ^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:04:22   File "/app/adrfinder/fetch_site_status.py", line 44, in get_auth_cookie
2023-01-15 02:04:22     raise Exception("Request failed, Non-200 received getting AUTH cookie: {}".format(response.status))
2023-01-15 02:04:22 Exception: Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:08:36 (1) wsgi starting up on http://0.0.0.0:5500
2023-01-15 02:04:22 >> Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:08:36 >> Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:08:42 >> Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:08:36 Exception in thread Thread-5:
2023-01-15 02:08:36 Traceback (most recent call last):
2023-01-15 02:08:36   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
2023-01-15 02:08:36     self.run()
2023-01-15 02:08:36   File "/app/adrfinder/update_worker.py", line 26, in run
2023-01-15 02:08:36     update_handler = fetch_site_status.perform_site_check(datastore=self.datastore)
2023-01-15 02:08:36                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:08:36   File "/app/adrfinder/fetch_site_status.py", line 16, in __init__
2023-01-15 02:08:36     self.headers = self.get_auth_cookie()
2023-01-15 02:08:36                    ^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:08:36   File "/app/adrfinder/fetch_site_status.py", line 44, in get_auth_cookie
2023-01-15 02:08:36     raise Exception("Request failed, Non-200 received getting AUTH cookie: {}".format(response.status))
2023-01-15 02:08:36 Exception: Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:08:42 (1) accepted ('172.19.0.1', 52154)
2023-01-15 02:08:42 (1) accepted ('172.19.0.1', 52156)
2023-01-15 02:08:42 172.19.0.1 - - [15/Jan/2023 02:08:42] "GET / HTTP/1.1" 200 0 0.118876
2023-01-15 02:08:42 wsgi exiting
2023-01-15 02:08:42 (1) wsgi exited, is_accepting=True
2023-01-15 02:11:24 (1) wsgi starting up on http://0.0.0.0:5500
2023-01-15 02:11:24 Exception in thread Thread-5:
2023-01-15 02:11:24 Traceback (most recent call last):
2023-01-15 02:11:24   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
2023-01-15 02:11:24     self.run()
2023-01-15 02:11:24   File "/app/adrfinder/update_worker.py", line 26, in run
2023-01-15 02:11:24     update_handler = fetch_site_status.perform_site_check(datastore=self.datastore)
2023-01-15 02:11:24                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:11:24   File "/app/adrfinder/fetch_site_status.py", line 16, in __init__
2023-01-15 02:11:24     self.headers = self.get_auth_cookie()
2023-01-15 02:11:24                    ^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:11:24   File "/app/adrfinder/fetch_site_status.py", line 44, in get_auth_cookie
2023-01-15 02:11:24     raise Exception("Request failed, Non-200 received getting AUTH cookie: {}".format(response.status))
2023-01-15 02:11:24 Exception: Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:11:26 (1) accepted ('172.19.0.1', 52444)
2023-01-15 02:11:26 (1) accepted ('172.19.0.1', 52446)
2023-01-15 02:11:26 172.19.0.1 - - [15/Jan/2023 02:11:26] "GET / HTTP/1.1" 200 0 0.077326
2023-01-15 02:11:26 wsgi exiting
2023-01-15 02:11:26 (1) wsgi exited, is_accepting=True
2023-01-15 02:16:54 (1) wsgi starting up on http://0.0.0.0:5500
2023-01-15 02:16:54 Exception in thread Thread-5:
2023-01-15 02:16:54 Traceback (most recent call last):
2023-01-15 02:16:54   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
2023-01-15 02:16:54     self.run()
2023-01-15 02:16:54   File "/app/adrfinder/update_worker.py", line 26, in run
2023-01-15 02:16:54     update_handler = fetch_site_status.perform_site_check(datastore=self.datastore)
2023-01-15 02:16:54                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:16:54   File "/app/adrfinder/fetch_site_status.py", line 16, in __init__
2023-01-15 02:16:54     self.headers = self.get_auth_cookie()
2023-01-15 02:16:54                    ^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:16:54   File "/app/adrfinder/fetch_site_status.py", line 44, in get_auth_cookie
2023-01-15 02:11:24 >> Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:11:26 >> Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:16:54 >> Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:16:56 >> Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:28:36 >> Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:31:14 >> Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:16:54     raise Exception("Request failed, Non-200 received getting AUTH cookie: {}".format(response.status))
2023-01-15 02:16:54 Exception: Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:16:56 (1) accepted ('172.19.0.1', 52500)
2023-01-15 02:16:56 (1) accepted ('172.19.0.1', 52502)
2023-01-15 02:16:56 172.19.0.1 - - [15/Jan/2023 02:16:56] "GET / HTTP/1.1" 200 0 0.088068
2023-01-15 02:16:56 wsgi exiting
2023-01-15 02:16:56 (1) wsgi exited, is_accepting=True
2023-01-15 02:28:35 (1) wsgi starting up on http://0.0.0.0:5500
2023-01-15 02:28:36 Exception in thread Thread-5:
2023-01-15 02:28:36 Traceback (most recent call last):
2023-01-15 02:28:36   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
2023-01-15 02:28:36     self.run()
2023-01-15 02:28:36   File "/app/adrfinder/update_worker.py", line 26, in run
2023-01-15 02:28:36     update_handler = fetch_site_status.perform_site_check(datastore=self.datastore)
2023-01-15 02:28:36                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:28:36   File "/app/adrfinder/fetch_site_status.py", line 16, in __init__
2023-01-15 02:28:36     self.headers = self.get_auth_cookie()
2023-01-15 02:28:36                    ^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:28:36   File "/app/adrfinder/fetch_site_status.py", line 44, in get_auth_cookie
2023-01-15 02:28:36     raise Exception("Request failed, Non-200 received getting AUTH cookie: {}".format(response.status))
2023-01-15 02:28:36 Exception: Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:31:14 (1) wsgi starting up on http://0.0.0.0:5500
2023-01-15 02:31:14 Exception in thread Thread-5:
2023-01-15 02:31:14 Traceback (most recent call last):
2023-01-15 02:31:14   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
2023-01-15 02:31:14     self.run()
2023-01-15 02:31:14   File "/app/adrfinder/update_worker.py", line 26, in run
2023-01-15 02:31:14     update_handler = fetch_site_status.perform_site_check(datastore=self.datastore)
2023-01-15 02:31:14                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:31:14   File "/app/adrfinder/fetch_site_status.py", line 16, in __init__
2023-01-15 02:31:14     self.headers = self.get_auth_cookie()
2023-01-15 02:31:14                    ^^^^^^^^^^^^^^^^^^^^^^
2023-01-15 02:31:14   File "/app/adrfinder/fetch_site_status.py", line 44, in get_auth_cookie
2023-01-15 02:31:14     raise Exception("Request failed, Non-200 received getting AUTH cookie: {}".format(response.status))
2023-01-15 02:31:14 Exception: Request failed, Non-200 received getting AUTH cookie: 302
2023-01-15 02:31:20 (1) accepted ('172.19.0.1', 52772)
2023-01-15 02:31:20 (1) accepted ('172.19.0.1', 52770)
2023-01-15 02:31:20 172.19.0.1 - - [15/Jan/2023 02:31:20] "GET / HTTP/1.1" 200 0 0.098403
2023-01-15 02:31:20 wsgi exiting
2023-01-15 02:31:20 (1) wsgi exited, is_accepting=True
2023-01-15 02:31:20 >> Request failed, Non-200 received getting AUTH cookie: 302

**Comment by MaxTheComputerer** [comment]
I am also experiencing this issue today (WSL Ubuntu), both when using the Docker image, and when running locally (tested with Python 3.8.10, 3.10.11, and 3.11.3).

**Comment by ChuckMac** [comment]
ah interesting it must do geolocation then

**Comment by ChuckMac** [comment]
I was able to run the container with a UK VPN and recreate the issue.  Will see what can be done to address.

**Comment by ChuckMac** [comment]
@MaxTheComputerer try to pull the latest release, should address it.

**Comment by MaxTheComputerer** [comment]
That works perfectly! Thanks for a great repo and for the quick fix :)
