### ISSUE TITLE
Doesn't load

### ISSUE THREAD

**Issue by dawnerd** [ChuckMac/ADRFinder#17]
Got a brand new setup following the readme using docker compose on mac, all latest.

```
troywhiteley@FastBookPro:~/Projects/ADRFinder$ docker compose logs
adrfinder  | Creating JSON store at /datastore
adrfinder  | (1) wsgi starting up on http://0.0.0.0:5500
adrfinder  | (1) accepted ('172.22.0.1', 60092)
```

When hitting the url Chrome and Safari just spin forever.

```
troywhiteley@FastBookPro:~/Projects/ADRFinder$ wget http://localhost:5500/
--2023-04-17 15:32:08--  http://localhost:5500/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:5500... connected.
HTTP request sent, awaiting response...
```

Also set this up on my other server that had this running before and it does the same thing.

**Comment by dawnerd** [comment]
Followup, it did eventually load with the following error stack:

```
adrfinder  | Exception in thread Thread-5:
adrfinder  | Traceback (most recent call last):
adrfinder  |   File "/usr/local/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
adrfinder  |     self.run()
adrfinder  |   File "/app/adrfinder/update_worker.py", line 26, in run
adrfinder  |     update_handler = fetch_site_status.perform_site_check(datastore=self.datastore)
adrfinder  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/fetch_site_status.py", line 16, in __init__
adrfinder  |     self.headers = self.get_auth_cookie()
adrfinder  |                    ^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/fetch_site_status.py", line 40, in get_auth_cookie
adrfinder  |     response = connection.getresponse()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 1375, in getresponse
adrfinder  |     response.begin()
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
adrfinder  |     version, status, reason = self._read_status()
adrfinder  |                               ^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
adrfinder  |     raise RemoteDisconnected("Remote end closed connection without"
adrfinder  | http.client.RemoteDisconnected: Remote end closed connection without response
adrfinder  | ERROR:adrfinder:Exception on / [GET]
adrfinder  | Traceback (most recent call last):
adrfinder  |   File "/usr/local/flask/app.py", line 2528, in wsgi_app
adrfinder  |     response = self.full_dispatch_request()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1825, in full_dispatch_request
adrfinder  |     rv = self.handle_user_exception(e)
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1823, in full_dispatch_request
adrfinder  |     rv = self.dispatch_request()
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1799, in dispatch_request
adrfinder  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask_login/utils.py", line 290, in decorated_view
adrfinder  |     return current_app.ensure_sync(func)(*args, **kwargs)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 350, in index
adrfinder  |     rest_and_times = get_restaurants_and_times()
adrfinder  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 1018, in get_restaurants_and_times
adrfinder  |     rest = Restaurants()
adrfinder  |            ^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 10, in __init__
adrfinder  |     self.header = self.get_auth_cookie()
adrfinder  |                   ^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 28, in get_auth_cookie
adrfinder  |     response = connection.getresponse()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 1375, in getresponse
adrfinder  |     response.begin()
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
adrfinder  |     version, status, reason = self._read_status()
adrfinder  |                               ^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
adrfinder  |     raise RemoteDisconnected("Remote end closed connection without"
adrfinder  | http.client.RemoteDisconnected: Remote end closed connection without response
adrfinder  | 172.22.0.1 - - [17/Apr/2023 22:35:42] "GET / HTTP/1.1" 500 425 600.575905
adrfinder  | ERROR:adrfinder:Exception on / [GET]
adrfinder  | Traceback (most recent call last):
adrfinder  |   File "/usr/local/flask/app.py", line 2528, in wsgi_app
adrfinder  |     response = self.full_dispatch_request()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1825, in full_dispatch_request
adrfinder  |     rv = self.handle_user_exception(e)
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1823, in full_dispatch_request
adrfinder  |     rv = self.dispatch_request()
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1799, in dispatch_request
adrfinder  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask_login/utils.py", line 290, in decorated_view
adrfinder  |     return current_app.ensure_sync(func)(*args, **kwargs)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 350, in index
adrfinder  |     rest_and_times = get_restaurants_and_times()
adrfinder  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 1018, in get_restaurants_and_times
adrfinder  |     rest = Restaurants()
adrfinder  |            ^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 10, in __init__
adrfinder  |     self.header = self.get_auth_cookie()
adrfinder  |                   ^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 28, in get_auth_cookie
adrfinder  |     response = connection.getresponse()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 1375, in getresponse
adrfinder  |     response.begin()
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
adrfinder  |     version, status, reason = self._read_status()
adrfinder  |                               ^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
adrfinder  |     raise RemoteDisconnected("Remote end closed connection without"
adrfinder  | http.client.RemoteDisconnected: Remote end closed connection without response
adrfinder  | 172.22.0.1 - - [17/Apr/2023 22:36:06] "GET / HTTP/1.1" 500 425 600.460092
adrfinder  | ERROR:adrfinder:Exception on / [GET]
adrfinder  | Traceback (most recent call last):
adrfinder  |   File "/usr/local/flask/app.py", line 2528, in wsgi_app
adrfinder  |     response = self.full_dispatch_request()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1825, in full_dispatch_request
adrfinder  |     rv = self.handle_user_exception(e)
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1823, in full_dispatch_request
adrfinder  |     rv = self.dispatch_request()
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1799, in dispatch_request
adrfinder  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask_login/utils.py", line 290, in decorated_view
adrfinder  |     return current_app.ensure_sync(func)(*args, **kwargs)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 350, in index
adrfinder  |     rest_and_times = get_restaurants_and_times()
adrfinder  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 1018, in get_restaurants_and_times
adrfinder  |     rest = Restaurants()
adrfinder  |            ^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 10, in __init__
adrfinder  |     self.header = self.get_auth_cookie()
adrfinder  |                   ^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 28, in get_auth_cookie
adrfinder  |     response = connection.getresponse()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 1375, in getresponse
adrfinder  |     response.begin()
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
adrfinder  |     version, status, reason = self._read_status()
adrfinder  |                               ^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
adrfinder  |     raise RemoteDisconnected("Remote end closed connection without"
adrfinder  | http.client.RemoteDisconnected: Remote end closed connection without response
adrfinder  | 172.22.0.1 - - [17/Apr/2023 22:39:21] "GET / HTTP/1.1" 500 425 600.649313
adrfinder  | ERROR:adrfinder:Exception on / [GET]
adrfinder  | Traceback (most recent call last):
adrfinder  |   File "/usr/local/flask/app.py", line 2528, in wsgi_app
adrfinder  |     response = self.full_dispatch_request()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1825, in full_dispatch_request
adrfinder  |     rv = self.handle_user_exception(e)
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1823, in full_dispatch_request
adrfinder  |     rv = self.dispatch_request()
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1799, in dispatch_request
adrfinder  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask_login/utils.py", line 290, in decorated_view
adrfinder  |     return current_app.ensure_sync(func)(*args, **kwargs)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 350, in index
adrfinder  |     rest_and_times = get_restaurants_and_times()
adrfinder  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 1018, in get_restaurants_and_times
adrfinder  |     rest = Restaurants()
adrfinder  |            ^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 10, in __init__
adrfinder  |     self.header = self.get_auth_cookie()
adrfinder  |                   ^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 28, in get_auth_cookie
adrfinder  |     response = connection.getresponse()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 1375, in getresponse
adrfinder  |     response.begin()
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
adrfinder  |     version, status, reason = self._read_status()
adrfinder  |                               ^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
adrfinder  |     raise RemoteDisconnected("Remote end closed connection without"
adrfinder  | http.client.RemoteDisconnected: Remote end closed connection without response
adrfinder  | 172.22.0.1 - - [17/Apr/2023 22:39:27] "GET / HTTP/1.1" 500 425 600.271161
adrfinder  | ERROR:adrfinder:Exception on / [GET]
adrfinder  | Traceback (most recent call last):
adrfinder  |   File "/usr/local/flask/app.py", line 2528, in wsgi_app
adrfinder  |     response = self.full_dispatch_request()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1825, in full_dispatch_request
adrfinder  |     rv = self.handle_user_exception(e)
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1823, in full_dispatch_request
adrfinder  |     rv = self.dispatch_request()
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1799, in dispatch_request
adrfinder  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask_login/utils.py", line 290, in decorated_view
adrfinder  |     return current_app.ensure_sync(func)(*args, **kwargs)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 350, in index
adrfinder  |     rest_and_times = get_restaurants_and_times()
adrfinder  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 1018, in get_restaurants_and_times
adrfinder  |     rest = Restaurants()
adrfinder  |            ^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 10, in __init__
adrfinder  |     self.header = self.get_auth_cookie()
adrfinder  |                   ^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 28, in get_auth_cookie
adrfinder  |     response = connection.getresponse()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 1375, in getresponse
adrfinder  |     response.begin()
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
adrfinder  |     version, status, reason = self._read_status()
adrfinder  |                               ^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
adrfinder  |     raise RemoteDisconnected("Remote end closed connection without"
adrfinder  | http.client.RemoteDisconnected: Remote end closed connection without response
adrfinder  | 172.22.0.1 - - [17/Apr/2023 22:39:33] "GET / HTTP/1.1" 500 425 600.751158
adrfinder  | ERROR:adrfinder:Exception on / [GET]
adrfinder  | Traceback (most recent call last):
adrfinder  |   File "/usr/local/flask/app.py", line 2528, in wsgi_app
adrfinder  |     response = self.full_dispatch_request()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1825, in full_dispatch_request
adrfinder  |     rv = self.handle_user_exception(e)
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1823, in full_dispatch_request
adrfinder  |     rv = self.dispatch_request()
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1799, in dispatch_request
adrfinder  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask_login/utils.py", line 290, in decorated_view
adrfinder  |     return current_app.ensure_sync(func)(*args, **kwargs)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 350, in index
adrfinder  |     rest_and_times = get_restaurants_and_times()
adrfinder  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 1018, in get_restaurants_and_times
adrfinder  |     rest = Restaurants()
adrfinder  |            ^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 10, in __init__
adrfinder  |     self.header = self.get_auth_cookie()
adrfinder  |                   ^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 28, in get_auth_cookie
adrfinder  |     response = connection.getresponse()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 1375, in getresponse
adrfinder  |     response.begin()
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
adrfinder  |     version, status, reason = self._read_status()
adrfinder  |                               ^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
adrfinder  |     raise RemoteDisconnected("Remote end closed connection without"
adrfinder  | http.client.RemoteDisconnected: Remote end closed connection without response
adrfinder  | 172.22.0.1 - - [17/Apr/2023 22:41:46] "GET / HTTP/1.1" 500 425 600.817758
adrfinder  | 172.22.0.1 - - [17/Apr/2023 22:41:46] "GET /favicon.ico HTTP/1.1" 200 112335 0.003797
adrfinder  | ERROR:adrfinder:Exception on / [GET]
adrfinder  | Traceback (most recent call last):
adrfinder  |   File "/usr/local/flask/app.py", line 2528, in wsgi_app
adrfinder  |     response = self.full_dispatch_request()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1825, in full_dispatch_request
adrfinder  |     rv = self.handle_user_exception(e)
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1823, in full_dispatch_request
adrfinder  |     rv = self.dispatch_request()
adrfinder  |          ^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask/app.py", line 1799, in dispatch_request
adrfinder  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/flask_login/utils.py", line 290, in decorated_view
adrfinder  |     return current_app.ensure_sync(func)(*args, **kwargs)
adrfinder  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 350, in index
adrfinder  |     rest_and_times = get_restaurants_and_times()
adrfinder  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/__init__.py", line 1018, in get_restaurants_and_times
adrfinder  |     rest = Restaurants()
adrfinder  |            ^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 10, in __init__
adrfinder  |     self.header = self.get_auth_cookie()
adrfinder  |                   ^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/app/adrfinder/restaurants.py", line 28, in get_auth_cookie
adrfinder  |     response = connection.getresponse()
adrfinder  |                ^^^^^^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 1375, in getresponse
adrfinder  |     response.begin()
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
adrfinder  |     version, status, reason = self._read_status()
adrfinder  |                               ^^^^^^^^^^^^^^^^^^^
adrfinder  |   File "/usr/local/lib/python3.11/http/client.py", line 287, in _read_status
adrfinder  |     raise RemoteDisconnected("Remote end closed connection without"
adrfinder  | http.client.RemoteDisconnected: Remote end closed connection without response
adrfinder  | 172.22.0.1 - - [17/Apr/2023 22:42:09] "GET / HTTP/1.1" 500 425 601.027019
```

**Comment by netpappy** [comment]
I just tested it on a different Mac (didn't even have docker installed at first), and it worked for me... When you ran the compose command did it complete the pull? Here is my example: 
```
netpappy@Mac-mini ADRFinder % docker-compose up -d
[+] Running 13/13
 ✔ adrfinder 12 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled              11.3s 
   ✔ ebc3dc5a2d72 Pull complete                                            2.7s 
   ✔ 03005f146bfb Pull complete                                            2.8s 
   ✔ 4a6241eb8776 Pull complete                                            3.2s 
   ✔ dc63d7810713 Pull complete                                            3.2s 
   ✔ 510f1ec7a0b2 Pull complete                                            3.4s 
   ✔ 32afb18016a4 Pull complete                                            9.2s 
   ✔ 56f3e9d354b1 Pull complete                                            9.3s 
   ✔ c1af15651cde Pull complete                                            9.3s 
   ✔ 1f80945743fb Pull complete                                            9.8s 
   ✔ f0396ea86f51 Pull complete                                            9.8s 
   ✔ e3ac6875981a Pull complete                                            9.9s 
   ✔ 4f4fb700ef54 Pull complete                                            9.9s 
[+] Running 2/2
 ✔ Network adrfinder_default  Created                                      0.0s 
 ✔ Container adrfinder        Started                                      4.1s 

```

If the pull didn't complete you might want to try the pull and compose again with the following command...

`docker-compose pull && docker-compose up -d`

**Comment by dawnerd** [comment]
Yep pulled latest, tried on another server on my same network and it also stalls with the same message:

```
troy@oldie:~/ADRFinder$ docker compose pull && docker compose up
[+] Running 13/13
 ✔ adrfinder 12 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                             6.9s 
   ✔ 26c5c85e47da Pull complete                                                                                                                                                          1.8s 
   ✔ 9e79879be9c7 Pull complete                                                                                                                                                          2.0s 
   ✔ 5dd57ff8d411 Pull complete                                                                                                                                                          2.3s 
   ✔ 50349b1ecdeb Pull complete                                                                                                                                                          2.4s 
   ✔ 431f8d1d6c10 Pull complete                                                                                                                                                          2.5s 
   ✔ 6b6621cdeded Pull complete                                                                                                                                                          4.8s 
   ✔ 8a3d29c66d6f Pull complete                                                                                                                                                          4.8s 
   ✔ d476731fe681 Pull complete                                                                                                                                                          4.9s 
   ✔ 418ed88cf577 Pull complete                                                                                                                                                          5.5s 
   ✔ 5fef6e21a47a Pull complete                                                                                                                                                          5.6s 
   ✔ 331a4065f405 Pull complete                                                                                                                                                          5.6s 
   ✔ 4f4fb700ef54 Pull complete                                                                                                                                                          5.6s 
[+] Running 2/0
 ✔ Network adrfinder_default  Created                                                                                                                                                    0.1s 
 ✔ Container adrfinder        Created                                                                                                                                                    0.0s 
Attaching to adrfinder
adrfinder  | Creating JSON store at /datastore
adrfinder  | (1) wsgi starting up on http://0.0.0.0:5500
adrfinder  | (1) accepted ('172.19.0.1', 58622)
```

It seems its the first request it makes to the Disney api. Wondering if they're doing some sort of bot detection

**Comment by kingstonlee** [comment]
I ran into the same issue and tested running from different environments.  It looks like there's an issue making calls from DigitalOcean to Disney.  When I tested it on other environments, it looked like it worked from Azure and AWS networks.

@dawnerd - Just curious whether you were using a cloud environment or if the failure was from running on your local ISP.
