### ISSUE TITLE
Restarting(1)

### ISSUE THREAD

**Issue by viajb** [ChuckMac/ADRFinder#23]
**Describe the bug**
Running fastest version of ADRFinder 0.2.9.1 on Docker Desktop MAC

container is in a restart look with the error below:

2023-10-04 09:30:58 Traceback (most recent call last):
2023-10-04 09:30:58   File "/app/./adrfinder.py", line 11, in <module>
2023-10-04 09:30:58     import adrfinder
2023-10-04 09:30:58   File "/app/adrfinder/__init__.py", line 21, in <module>
2023-10-04 09:30:58     import flask_login
2023-10-04 09:30:58   File "/usr/local/flask_login/__init__.py", line 12, in <module>
2023-10-04 09:30:58     from .login_manager import LoginManager
2023-10-04 09:30:58   File "/usr/local/flask_login/login_manager.py", line 33, in <module>
2023-10-04 09:30:58     from .utils import _create_identifier
2023-10-04 09:30:58   File "/usr/local/flask_login/utils.py", line 14, in <module>
2023-10-04 09:30:58     from werkzeug.urls import url_decode
2023-10-04 09:30:58 ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/werkzeug/urls.py)

**Comment by tchmnkyz** [comment]
I was able to find the issue and fix this. I am sending in a PR for this now.

**Comment by tchmnkyz** [comment]
Ok Created a PR to merge the fix in: https://github.com/ChuckMac/ADRFinder/pull/24 @ChuckMac @viajb
